<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.10" />
    <PackageReference Include="NaturalSort.Extension" Version="4.4.1" />
    <PackageReference Include="PDFsharp" Version="6.2.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PagePdf.Application\PagePdf.Application.csproj" />
  </ItemGroup>

</Project>
