<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Headless.XUnit" Version="11.3.18" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\PagePdf.UI\PagePdf.UI.csproj" />
  </ItemGroup>

</Project>
